#!/bin/bash
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /var/jb/Library/MobileSubstrate/DynamicLibraries/GumJSWebSocket.dylib
    rm -f /var/jb/Library/MobileSubstrate/DynamicLibraries/GumJSWebSocket.plist
    rm -f /var/jb/usr/lib/libGJWSEngine.dylib
    rm -rf /var/jb/Library/PreferenceBundles/GJWSPreferences.bundle
    rm -f /var/jb/Library/PreferenceLoader/Preferences/GJWSPreferences.plist
    rm -f /var/mobile/Library/Preferences/com.gjws.config.plist

    sbreload 2>/dev/null || killall -9 SpringBoard 2>/dev/null || true
fi
exit 0
